### PR TITLE
Feature/async

### PR DESCRIPTION
**Pull request by D0tNet4Fun**
Hello,

This is another attempt at issue #1 . I added task-based methods for the ones that now follow the APM pattern (Begin/End). I.e. method `BackupComplete` can be run async using the new method `BackupCompleteAsync`, instead of using `BeginBackupComplete` and `EndBackupComplete`. 

How it works: The VSS method `BackupComplete` is executed on the caller's thread, then a task is scheduled to wait for completion on another thread and the task is returned to the caller. The caller can then await the task. (See examples in AlphaShadow).

Features:
- the task scheduling is managed by a  task factory that the user can set using `VssUtils.TaskFactory`. This should be done once per app. When tasks are scheduled, they use this factory's task scheduler. In case the task factory is not set by user, a default task factory is used whose task scheduler is `TaskScheduler.Default` (the one that uses threads from the thread pool).
- each async method can use a `CancellationToken` to cancel the operation async.

I didn't add documentation yet. I will do so if you agree on these changes.

Hope this helps.

### CODE REVIEW

**Comment by D0tNet4Fun** [comment]
I just refactored the code in order to avoid an issue with unobserved tasks.

Note: the build fails because I used a NuGet package in AlphaShadow and the AppVeyor build should restore the packages prior to running the build. This is not something I can change in the source code. See https://www.appveyor.com/blog/2014/03/18/about-nuget-package-restore.

**Comment by alphaleonis** [comment]
Thanks for the PR, and sorry for the late reply. I'll hopefully get around to having a look at it this weekend. (Wasn't even aware I had setup an appveyor build for this, but it's probably incomplete just as you apparently noticed. :)

**Comment by alphaleonis** [comment]
Better late than never I suppose. Async support has now been implemented. I had to do it manually rather than use your PR because of many other changes that were simultaneously made. But I took inspiration from your code. So thank you for the PR, and I really apologize for waiting this long.

**Comment by D0tNet4Fun** [comment]
That's OK. Thank you for adding async support.

**Pull request closed without merging**
